### ISSUE TITLE
'TypeError' with message 'rias\ssg\Generator::rias\ssg\{closure}(): Argument #1 ($error) must be of type string, Closure given, called in /var/www/html/vendor/illuminate/collections/Traits/EnumeratesValues.php on line 240'

### ISSUE THREAD

**Issue by craftunit-liam** [riasvdv/craft-ssg#1]
Hi there!

I wanted to try out the plugin and got this error when running "ddev php craft ssg/static/generate".
```
ℹ️ Gathering content...
ℹ️ Generating 65 content files: [===================================================================================================================================] 100% (65/65) ETA: 1 sec.
✅  Generated 0 content files
Exception 'TypeError' with message 'rias\ssg\Generator::rias\ssg\{closure}(): Argument #1 ($error) must be of type string, Closure given, called in /var/www/html/vendor/illuminate/collections/Traits/EnumeratesValues.php on line 240'

in /var/www/html/vendor/rias/craft-ssg/src/Generator.php:143

Stack trace:
#0 /var/www/html/vendor/illuminate/collections/Traits/EnumeratesValues.php(240): rias\ssg\Generator->rias\ssg\{closure}()
#1 /var/www/html/vendor/rias/craft-ssg/src/Generator.php(143): Illuminate\Support\Collection->each()
#2 /var/www/html/vendor/rias/craft-ssg/src/Generator.php(92): rias\ssg\Generator->createContent()
#3 /var/www/html/vendor/rias/craft-ssg/src/console/controllers/StaticController.php(63): rias\ssg\Generator->generate()
#4 [internal function]: rias\ssg\console\controllers\StaticController->actionGenerate()
#5 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#6 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#7 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction()
#8 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(89): yii\console\Controller->runAction()
#9 /var/www/html/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction()
#10 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction()
#11 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction()
#12 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction()
#13 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction()
#14 /var/www/html/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest()
#15 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest()
#16 /var/www/html/craft(13): yii\base\Application->run()
#17 {main}
Failed to run php craft ssg/static/generate: exit status 1
```

```json, composer.json
  "require": {
    "craftcms/ckeditor": "4.2.0",
    "craftcms/cms": "5.4.1",
    "dodecastudio/craft-blurhash": "^3.0.0",
    "doublesecretagency/craft-cpcss": "3.0.0",
    "ether/seo": "v5.0.0-rc5",
    "rias/craft-ssg": "1.0.1",
    "vlucas/phpdotenv": "^5.4.0",
    "voku/html-min": "^4.0.0"
  },
  "require-dev": {
    "craftcms/generator": "^2.0.0",
    "yiisoft/yii2-shell": "^2.0.3"
  },
  "autoload": {
    "psr-4": {
      "modules\\": "modules/"
    }
  },
  "config": {
    "allow-plugins": {
      "craftcms/plugin-installer": true,
      "yiisoft/yii2-composer": true,
      "treeware/plant": true
    },
    "sort-packages": true,
    "optimize-autoloader": true,
    "platform": {
      "php": "8.3"
    }
  },
  "scripts": {
    "post-root-package-install": [
      "@php -r \"file_exists('.env') || copy('.env.example.dev', '.env');\""
    ]
  },
  "repositories": [
    {
      "type": "composer",
      "url": "https://composer.craftcms.com",
      "canonical": false
    }
  ]
}
```
Here is an excerpt from the ddev config
```YAML
type: craftcms
docroot: web
php_version: "8.3"
webserver_type: apache-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.6"
use_dns_when_possible: true
composer_version: "2"
web_environment:
    - APACHE_ARGUMENTS=-Ddevelopment
```

**Comment by riasvdv** [comment]
Should be fixed in 1.0.2! Thanks for reporting this
